export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const USER_LOADED = "USER_LOADED";
export const USERS_LOADED = "USERS_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const GET_REPOS = "GET_REPOS";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";

export const ACCOUNT_DELETED = "ACCOUNT_DELETED";

export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";
export const POST_ERROR = "POST_ERROR";
export const UPDATE_LIKES = "UPDATE_LIKES";
export const ADD_POST = "ADD_POST";
export const DELETE_POST = "DELETE_POST";

export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";

export const GET_IMAGE = "GET_IMAGE";
export const GET_IMAGES = "GET_IMAGES";
export const IMAGE_ERROR = "IMAGE_ERROR";
export const UPDATE_IMAGE = "UPDATE_IMAGE";
export const CLEAR_IMAGE = "CLEAR_IMAGE";
export const DELETE_IMAGE = "DELETE_IMAGE";

export const GET_GOOGLEALBUM = "GET_GOOGLEALBUM";
export const GET_GOOGLEALBUMS = "GET_GOOGLEALBUMS";
export const GOOGLEALBUM_ERROR = "GOOGLEALBUM_ERROR";
export const UPDATE_GOOGLEALBUM = "UPDATE_GOOGLEALBUM";
export const CLEAR_GOOGLEALBUM = "CLEAR_GOOGLEALBUM";
export const DELETE_GOOGLEALBUM = "DELETE_GOOGLEALBUM";

export const GET_DAYCARE = "GET_DAYCARE";
export const GET_DAYCARES = "GET_DAYCARES";
export const DAYCARE_ERROR = "DAYCARE_ERROR";
export const UPDATE_DAYCARE = "UPDATE_DAYCARE";
export const CLEAR_DAYCARE = "CLEAR_DAYCARE";
export const DELETE_DAYCARE = "DELETE_DAYCARE";

export const GET_CLASSROOM = "GET_CLASSROOM";
export const GET_CLASSROOMS = "GET_CLASSROOMS";
export const CLASSROOM_ERROR = "CLASSROOM_ERROR";
export const UPDATE_CLASSROOM = "UPDATE_CLASSROOM";
export const CLEAR_CLASSROOMS = "CLEAR_CLASSROOMS";
export const DELETE_CLASSROOM = "DELETE_CLASSROOM";

export const GET_STUDENT = "GET_STUDENT";
export const GET_STUDENTS = "GET_STUDENTS";
export const STUDENT_ERROR = "STUDENT_ERROR";
export const STUDENTS_ERROR = "STUDENTS_ERROR";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const CLEAR_STUDENTS = "CLEAR_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
